language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

script:
  CODECLIMATE_REPO_TOKEN=25d03499fa4fad3f1edcd9d382e7a8d98a340b313cf9384ca2c679c8bf25d721 bundle exec rake
